# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Blackcat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller==4.10
        pip install -r requirements.txt

    # stop the build if there are Python syntax errors or undefined names
    - name: Lint with flake8
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

    # - name: transform ui to py with pyuic5
    #   run: |
    #     cd uiFiles
    #     pyuic5 -o ui_gameSettings.py ui_gs.ui
    #     pyuic5 -o ui_gameSettingShortcuts.py ui_gs_shortcuts.ui
    #     pyuic5 -o ui_defined_parameter.py ui_defined_parameter.ui
    #     pyuic5 -o ui_mine_num_bar.py ui_mine_num_bar.ui
    #     cd ..
    #     md src/ui
    #     cp uiFiles/ui_gameSettings.py src/ui/ui_gameSettings.py
    #     cp uiFiles/ui_gameSettingShortcuts.py src/ui/ui_gameSettingShortcuts.py
    #     cp uiFiles/ui_defined_parameter.py src/ui/ui_defined_parameter.py
    #     cp uiFiles/ui_mine_num_bar.py src/ui/ui_mine_num_bar.py

    # - name: transform qrc to py with pyrcc5
    #   run: |
    #     cd src
    #     pyrcc5 src_help_pic.qrc -o src_help_pic_rc.py
    #     cd ..

    - name: Package with PyInstaller
      run: |
        pyinstaller -i cat.ico -w -y --clean --add-data "./src/media/*;./src/media" -p src src/main.py --onefile

    # upload the result package as an artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: blackcat-snapshot
        path: dist/
